services:
  postgres:
    image: postgres:13
    container_name: pg-metastore
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./analytics/output:/app/output 
  flask-app:
    build: ./Backend
    ports:
      - "5050:5000"
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: python app.py
    depends_on:
      - spark

  
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    
    ports:
      - "7077:7077"
      - "8088:8080"

    volumes:
      - ./spark:/opt/workspace
    command: bash -c "sleep infinity"
    entrypoint: ["tail", "-f", "/dev/null"]
    working_dir: /opt/workspace

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes

  generator:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: python generate_orders.py

volumes:
  pgdata:
#